
package Chap4;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Timer2 extends javax.swing.JFrame {

    int min = 0, sec = 0, hr = 0, min1, sec1, hr1;
    Timer timer;
    boolean isStop = false;
    
    public Timer2() {
        initComponents();
        for (int i = 0; i < 60; i++) {
            if (i < 10) {
                cbxHr.addItem("0" + i);
            }
            else {
                cbxHr.addItem("" + i);
            }
            
            if (i < 10) {
                cbxMin.addItem("0" + i);
            }
            else {
                cbxMin.addItem("" + i);
            }
            
            if (i < 10) {
                cbxSec.addItem("0" + i);
            }
            else {
                cbxSec.addItem("" + i);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        lblMin = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();
        lblSec = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHr = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxHr = new javax.swing.JComboBox<>();
        cbxMin = new javax.swing.JComboBox<>();
        cbxSec = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        btnMinAdd10 = new javax.swing.JButton();
        btnMinAdd15 = new javax.swing.JButton();
        btnMinAdd30 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KOT112");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblMin.setFont(new java.awt.Font("Qualy", 0, 48)); // NOI18N
        lblMin.setText("00");

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblSec.setFont(new java.awt.Font("Qualy", 0, 48)); // NOI18N
        lblSec.setText("00");

        jLabel11.setFont(new java.awt.Font("Earth Orbiter Title", 0, 26)); // NOI18N
        jLabel11.setText(" by Algorithm");

        jLabel5.setFont(new java.awt.Font("Qualy", 0, 48)); // NOI18N
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("Qualy", 0, 48)); // NOI18N
        jLabel6.setText(":");

        jLabel1.setFont(new java.awt.Font("Earth Orbiter Bold", 1, 34)); // NOI18N
        jLabel1.setText("Count down Timer");

        lblHr.setFont(new java.awt.Font("Qualy", 0, 48)); // NOI18N
        lblHr.setText("00");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Hour");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Minute");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Second");

        cbxHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHrActionPerformed(evt);
            }
        });

        cbxMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMinActionPerformed(evt);
            }
        });

        cbxSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSecActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnMinAdd10.setText("10 Minute");
        btnMinAdd10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinAdd10ActionPerformed(evt);
            }
        });

        btnMinAdd15.setText("15 Minute");
        btnMinAdd15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinAdd15ActionPerformed(evt);
            }
        });

        btnMinAdd30.setText("30 Minute");
        btnMinAdd30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinAdd30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbxHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(cbxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                    .addComponent(lblHr)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblSec)
                                    .addGap(73, 73, 73))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnStart)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnStop)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnReset)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnMinAdd10)
                                .addComponent(btnMinAdd15, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnMinAdd30, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHr)
                            .addComponent(lblMin)
                            .addComponent(lblSec)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart)
                            .addComponent(btnStop)
                            .addComponent(btnReset)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMinAdd10)
                        .addGap(7, 7, 7)
                        .addComponent(btnMinAdd15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinAdd30)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {                                         

        btnStart.setEnabled(false);
        btnMinAdd10.setEnabled(false);
        btnMinAdd15.setEnabled(false);
        btnMinAdd30.setEnabled(false);
        cbxHr.setEnabled(false);
        cbxMin.setEnabled(false);
        cbxSec.setEnabled(false);
        
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnStart.setEnabled(false);
                
                if (isStop) {
                    hr = hr1;
                    min = min1;
                    sec = sec1;
                    isStop = false;
                }
                if (sec < 1) {
                    sec = 60;
                    min--;
                }
                if (min < 0) {
                    min = 59;
                    hr--;
                }
                if (hr < 0) {
                    JOptionPane.showMessageDialog(rootPane, "Time Out!");
                    hr = 0;
                    min = 0;
                    sec = 0;
                    timer.stop();
                    btnStart.setEnabled(true);
                } else {
                    sec--;
                }
                if (sec < 10) {
                    lblSec.setText("0" + sec);
                } else {
                    lblSec.setText("" + sec);
                }

                if (min < 10) {
                    lblMin.setText("0" + min);
                } else {
                    lblMin.setText("" + min);
                }

                if (hr < 10) {
                    lblHr.setText("0" + hr);
                } else {
                    lblHr.setText("" + hr);
                }
            }
        });
        timer.start();
    }                                        

    private void cbxHrActionPerformed(java.awt.event.ActionEvent evt) {                                      
        lblHr.setText("" + cbxHr.getSelectedItem());
        hr = Integer.parseInt(lblHr.getText());
    }                                     

    private void cbxMinActionPerformed(java.awt.event.ActionEvent evt) {                                       
        lblMin.setText("" + cbxMin.getSelectedItem());
        min = Integer.parseInt(lblMin.getText());
    }                                      

    private void cbxSecActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
        lblSec.setText("" + cbxSec.getSelectedItem());
        sec = Integer.parseInt(lblSec.getText());
    }                                      

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {                                        
        min1 = min;
        sec1 = sec;
        hr1 = hr;
        isStop = true;
        timer.stop();
        btnStart.setEnabled(true);
    }                                       

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        hr = 0;
        hr1 = 0;
        min = 0;
        min1 = 0;
        sec = 0;
        sec1 = 0;
        lblHr.setText("0" + hr);
        lblMin.setText("0" + min);
        lblSec.setText("0" + sec);
        cbxHr.setEnabled(true);
        cbxMin.setEnabled(true);
        cbxSec.setEnabled(true);
        btnMinAdd10.setEnabled(true);
        btnMinAdd15.setEnabled(true);
        btnMinAdd30.setEnabled(true);
    }                                        

    private void btnMinAdd10ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        min = 10;
        lblMin.setText("" + min);
    }                                           

    private void btnMinAdd15ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        min = 15;
        lblMin.setText("" + min);
    }                                           

    private void btnMinAdd30ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        min = 30;
        lblMin.setText("" + min);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timer2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnMinAdd10;
    private javax.swing.JButton btnMinAdd15;
    private javax.swing.JButton btnMinAdd30;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox<String> cbxHr;
    private javax.swing.JComboBox<String> cbxMin;
    private javax.swing.JComboBox<String> cbxSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblHr;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSec;
    // End of variables declaration                   
}